:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

= C# attributes

== Enum Attribute

Any **type** in C# has an `Attributes` property which is of type `TypeAttributes` - it's a flag enum (meaning
it contains bit values).

This applies to POD types too, so we can print the `Attributes` property for int as follows:

[source,csharp]
----
using System;

namespace Att1
{
    class Program
    {
        private static void Main(string[] args)
        {
            var att = typeof(int).Attributes;
            Console.WriteLine($"{att}");
        }
    }
}
----

The result is:

----
AutoLayout, AnsiClass, Class, Public, SequentialLayout, Sealed, Serializable, BeforeFieldInit
----

== Custom Attributes

A class can have one or more custom attributes - a custom attribute is applied to a class using square brackets 
in the following way:

[source,csharp]
----
[ToastAttribute]
[EggAttribute]
class MyClass
{
}
----

Attributes can have parameterised constructors - the parameters must be simple types:

[source,csharp]
----
[ToastAttribute("Slice")]
class X
{
}
----

=== Defining attribute classes

An attribute is just an ordinary class with the condition that it must derive from `System.Attribute`.

An instance of the attribute class is created every time the reflection API `GetCustomAttributes` is 
used on the type. Using the reflection API `CustomAttributes` simply returns a collection of `System.Type` 
(without instantiating anything).

Thus the following code prints _Making toast_ twice:

[source,csharp]
----
using System;

namespace Att2
{
    class ToastAttribute : System.Attribute
    {
        public ToastAttribute()
        {
            Console.WriteLine("Making toast");
        }
    }

    [Toast]
    class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Program started");
            typeof(Program).GetCustomAttributes(true);
            typeof(Program).GetCustomAttributes(true);
            var atts = typeof(Program).CustomAttributes;
            Console.WriteLine();
        }
    }
}
----



